## Introduction to NumPy
!!! Dont forget to type `%config Completer.use_jedi = False` !!!

In [1]:
# Import numpy
import numpy as np

## Datatypes and attributes
    Numpy's main datatype is ndarray.
    It is also the only datatype.
    Ndarray stands for N dimensional array

### Quick note: Axis 1 refers to X axis, axis 0 refers to Y axis

In [2]:
a1 = np.array([1,2,3,4,5])
type(a1)

numpy.ndarray

In [3]:
a2 = np.array([[1,2,3],
               [1,2,3]])
a2

array([[1, 2, 3],
       [1, 2, 3]])

In [4]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

### Some attributes now

In [5]:
# Returns the shape of the array
a1.shape

(5,)

In [6]:
a2.shape

(2, 3)

In [7]:
a3.shape

(3, 2, 3)

In [8]:
# Returns the number of dimensions
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [9]:
# Returns the dataytpe
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [10]:
# Returns the size of the array / the amount of elements
a2.size, a2.size, a3.size

(6, 6, 18)

In [11]:
# This is just a python function, it shows that all of them are numpy arrays => dimension doesnt matter
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

### Creating a dataframe from a python array:
    -- Notes -- Must use a 2D array to make a dataframe, 3D arrays don't work

In [12]:
# importing pandas
import pandas as pd

dataFrame = pd.DataFrame(a2)
dataFrame

0  1  2
0  1  2  3
1  1  2  3

## Creating numpy arrays

In [13]:
sample_array = np.array([1,2,3 ])
sample_array

array([1, 2, 3])

In [14]:
sample_array.dtype

dtype('int32')

In [15]:
# Fills an array of a specific shape with ones
ones = np.ones(shape=(2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
type(ones)

numpy.ndarray

In [17]:
# Fills an array of a specific shape with zeroes
zeroes = np.zeros(shape=(2,3))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

### Usually we use zeroes arrays to have them as placeholders for real data, just to see the shape and stuff

In [18]:
# Returns an array made out of everyu number from start to finihs, with a step of step
range_array = np.arange(0, 10, 1)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# Returns an array with random numbers, from the lowest to the highest, with a specific size
random_array = np.random.randint(0, 100, (2,3))
random_array

array([[ 6, 79, 77],
       [48, 43, 35]])

In [20]:
# Returns an array made out of random vlaues in the interval 0.0, 1.0
# It is the equivalent of np.random.rand(shape)
random_random_array = np.random.random((2, 3))
random_random_array

array([[0.42659968, 0.09732115, 0.58697442],
       [0.06911507, 0.41480788, 0.09340929]])

In [21]:
# Pseudo-random numbers
# Random seed is used to set the seed, so that we can generate the same numbers everytime, so that we can always generate the 
# same numbers, which is usefull for recreating experiments.
np.random.seed(0)
random_array_4 = np.random.randint(0, 10, (2,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9]])

## Viewing arrays and matrices

In [31]:
# Create a ranom array
random_array_5 = np.random.randint(0, 10, (3,3))
random_array_5

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9]])

In [32]:
# Returns all of the unique elemnts of an array
np.unique(random_array_5)

array([1, 5, 6, 7, 8, 9])

In [35]:
# Just display the array to make it easier to see
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [37]:
# Same as python lists
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
# Slicing as in python lists
# Get first 2 elements of a3: a3[:2]
# Get the first rows out of both: a3[:2, :1]
# Get the first element of all: a3[:2, :1, :1]
a3[:2, :1, :1]

array([[[1]],

       [[7]]])

In [67]:
### !!! NOTES !!! Numpy reads size from right to left, meaning the size=[1,2,3] is equivalent( to my mind ) to [3,2,1]
random_array_6 = np.random.randint(0, 100, size=(1,2,3,4))
random_array_6

array([[[[80, 69, 79, 47],
         [64, 82, 99, 88],
         [49, 29, 19, 19]],

        [[14, 39, 32, 65],
         [ 9, 57, 32, 31],
         [74, 23, 35, 75]]]])

In [74]:
# EXERCISE: Get the first 4 items in the inner-most array:
# !!! simply ':' returns the entire array
random_array_6[:, :, :, :1]

array([[[[80],
         [64],
         [49]],

        [[14],
         [ 9],
         [74]]]])

## Manipulating & comparing arrays:

### Arithmetic

In [106]:
# Check, and create a new array
newOnes = np.ones(3)
a2 = np.random.randint(0, 100, (2,3))
a1 = np.random.randint(0, 100, 3)
a1, newOnes

(array([31,  1, 65]), array([1., 1., 1.]))

In [107]:
# Adding arrays
a1 + newOnes

array([32.,  2., 66.])

In [108]:
# Subtracting arrays:
a1 - newOnes

array([30.,  0., 64.])

In [109]:
# Multiplication:
a1 * newOnes

array([31.,  1., 65.])

In [110]:
# Checking with another array.
a1, "--newlinexD--", a2

(array([31,  1, 65]),
 '--newlinexD--',
 array([[38, 17, 79],
        [ 4, 42, 58]]))

In [113]:
# THEY MUST HAVE SAME SHAPE
# Multiplies index x in first to index x in second
a1 * a2

array([[1178,   17, 5135],
       [ 124,   42, 3770]])

In [118]:
# Another example
a2 * a3

array([[[  38,   34,  237],
        [  16,  210,  348]],

       [[ 266,  136,  711],
        [  40,  462,  696]],

       [[ 494,  238, 1185],
        [  64,  714, 1044]]])

In [119]:
new_array = np.random.randint(0, 100, (2, 3, 3))
new_array

array([[[41, 57, 35],
        [11, 46, 82],
        [91,  0, 14]],

       [[99, 53, 12],
        [42, 84, 75],
        [68,  6, 68]]])

In [124]:
# THIS GIVES AN ERROR, MEANING THAT WE SHOULD RESHAPE THE SECOND ARRAY
a2 * new_array

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [127]:
a2

array([[38, 17, 79],
       [ 4, 42, 58]])

In [132]:
new_array

array([[[41, 57, 35],
        [11, 46, 82],
        [91,  0, 14]],

       [[99, 53, 12],
        [42, 84, 75],
        [68,  6, 68]]])

In [133]:
# To reshape an array, we use array.reshape( value )
# NOTE: Since value is an array, if you multiply every item in the array, you must get the array.size !!!

In [134]:
a2 * new_array.reshape(3,2,3)

array([[[1558,  969, 2765],
        [  44, 1932, 4756]],

       [[3458,    0, 1106],
        [ 396, 2226,  696]],

       [[1596, 1428, 5925],
        [ 272,  252, 3944]]])

In [136]:
# Division:
a2 / a1

array([[ 1.22580645, 17.        ,  1.21538462],
       [ 0.12903226, 42.        ,  0.89230769]])

In [137]:
# Floor division ( floors the number to int )
a2 // a1

array([[ 1, 17,  1],
       [ 0, 42,  0]], dtype=int32)

In [140]:
# x-ing an array
a2 ** 2

array([[1444,  289, 6241],
       [  16, 1764, 3364]], dtype=int32)

#### Numpy has equivalent of all of the python arithmetic operations implemented such as: .sum(), .square(), .add()

In [141]:
# Some stuff idk what math this is:
np.exp(a1)

array([2.90488497e+13, 2.71828183e+00, 1.69488924e+28])

In [142]:
np.log(a1)

array([3.4339872 , 0.        , 4.17438727])

### Agegation